### ISSUE TITLE
Adjust to latest spdlog

### ISSUE THREAD

**Issue by Gryph201** [chadnickbok/librtcdcpp#31]
I was trying to install on my Ubuntu environment with the instructions provided "./configure make sudo make install" but the configure file appears to be missing. Is there something I'm doing incorrectly here?

**Comment by PowerInside** [comment]
The project uses CMake. Have the latest CMake installed (older ones can cause issues), and do something of the following from the project root:

`mkdir build_project && cd build_project`
`cmake ..`
and then
`make` or `make install`
`

**Comment by Gryph201** [comment]
Thanks for the quick reply! Unfortunately I did try running a cmake build with the project after I encountered my first problem and have been getting the following build error. 
`isaac@isaac-desktop:~/Projects/Repos/librtcdcpp/build$ sudo make
Scanning dependencies of target rtcdcpp
[  7%] Building CXX object CMakeFiles/rtcdcpp.dir/src/DataChannel.cpp.o
[ 15%] Building CXX object CMakeFiles/rtcdcpp.dir/src/DTLSWrapper.cpp.o
[ 23%] Building CXX object CMakeFiles/rtcdcpp.dir/src/Logging.cpp.o
[ 30%] Building CXX object CMakeFiles/rtcdcpp.dir/src/NiceWrapper.cpp.o
[ 38%] Building CXX object CMakeFiles/rtcdcpp.dir/src/PeerConnection.cpp.o
[ 46%] Building CXX object CMakeFiles/rtcdcpp.dir/src/RTCCertificate.cpp.o
[ 53%] Building CXX object CMakeFiles/rtcdcpp.dir/src/SCTPWrapper.cpp.o
[ 61%] Linking CXX shared library librtcdcpp.so
[ 61%] Built target rtcdcpp
Scanning dependencies of target testclient
[ 69%] Building CXX object examples/websocket_client/CMakeFiles/testclient.dir/easywsclient.cpp.o
[ 76%] Building CXX object examples/websocket_client/CMakeFiles/testclient.dir/jsoncpp.cpp.o
[ 84%] Building CXX object examples/websocket_client/CMakeFiles/testclient.dir/testclient.cpp.o
/home/isaac/Projects/Repos/librtcdcpp/examples/websocket_client/testclient.cpp: In function ‘int main()’:
/home/isaac/Projects/Repos/librtcdcpp/examples/websocket_client/testclient.cpp:37:112: error: no matching function for call to ‘make_shared(std::shared_ptr<spdlog::sinks::stdout_sink<std::mutex> >)’
 e_sink = std::make_shared<spdlog::sinks::ansicolor_sink>(spdlog::sinks::stdout_sink_mt::instance());
                                                                                                   ^
In file included from /usr/include/c++/6/memory:82:0,
                 from /home/isaac/Projects/Repos/librtcdcpp/examples/websocket_client/WebSocketWrapper.hpp:11,
                 from /home/isaac/Projects/Repos/librtcdcpp/examples/websocket_client/testclient.cpp:5:
/usr/include/c++/6/bits/shared_ptr.h:632:5: note: candidate: template<class _Tp, class ... _Args> std::shared_ptr<_Tp1> std::make_shared(_Args&& ...)
     make_shared(_Args&&... __args)
     ^~~~~~~~~~~
/usr/include/c++/6/bits/shared_ptr.h:632:5: note:   template argument deduction/substitution failed:
examples/websocket_client/CMakeFiles/testclient.dir/build.make:110: recipe for target 'examples/websocket_client/CMakeFiles/testclient.dir/testclient.cpp.o' failed
make[2]: *** [examples/websocket_client/CMakeFiles/testclient.dir/testclient.cpp.o] Error 1
CMakeFiles/Makefile2:122: recipe for target 'examples/websocket_client/CMakeFiles/testclient.dir/all' failed
make[1]: *** [examples/websocket_client/CMakeFiles/testclient.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
`
I'm trying to build on Ubuntu 16.04 LTS with cmake version 3.8.2. Any help would be greatly appreciated.

**Comment by PowerInside** [comment]
You could either disable the optional spdlog dependency by passing the `-DDISABLE_SPDLOG=on` flag to cmake or use an older version of spdlog (specifically, try [this commit](https://github.com/gabime/spdlog/tree/47006c4e8ed010adb402f302f12baae479842328)).

**Comment by gegles** [comment]
I just checked in a small tweak to adjust to the latest spdlog lib. Let me know.

**Comment by Gryph201** [comment]
That fixed the issue. Thanks
