### ISSUE TITLE
Error in build in EL6 (CentOS 6.5)

### ISSUE THREAD

**Issue by sibirchakraborty** [chadnickbok/librtcdcpp#29]
[root@localhost librtcdcpp]# make
[  7%] Building CXX object CMakeFiles/rtcdcpp.dir/src/DataChannel.cpp.o
In file included from /usr/include/spdlog/spdlog.h:12,
                 from /opt/Private/librtcdcpp/include/rtcdcpp/Logging.hpp:33,
                 from /opt/Private/librtcdcpp/include/rtcdcpp/PeerConnection.hpp:33,
                 from /opt/Private/librtcdcpp/src/DataChannel.cpp:35:
/usr/include/spdlog/common.h:12:18: error: atomic: No such file or directory
In file included from /opt/Private/librtcdcpp/include/rtcdcpp/DataChannel.hpp:34,
                 from /opt/Private/librtcdcpp/src/DataChannel.cpp:34:
/opt/Private/librtcdcpp/include/rtcdcpp/Chunk.hpp:41: error: function definition does not declare parameters
/opt/Private/librtcdcpp/include/rtcdcpp/Chunk.hpp:42: error: function definition does not declare parameters
/opt/Private/librtcdcpp/include/rtcdcpp/Chunk.hpp: In constructor ‘rtcdcpp::Chunk::Chunk(const void*, size_t)’:
/opt/Private/librtcdcpp/include/rtcdcpp/Chunk.hpp:49: error: class ‘rtcdcpp::Chunk’ does not have any field named ‘len’
/opt/Private/librtcdcpp/include/rtcdcpp/Chunk.hpp:49: error: class ‘rtcdcpp::Chunk’ does not have any field named ‘data’
/opt/Private/librtcdcpp/include/rtcdcpp/Chunk.hpp:49: error: ‘len’ was not declared in this scope
/opt/Private/librtcdcpp/include/rtcdcpp/Chunk.hpp:49: error: ‘data’ was not declared in this scope
/opt/Private/librtcdcpp/include/rtcdcpp/Chunk.hpp: In copy constructor ‘rtcdcpp::Chunk::Chunk(const rtcdcpp::Chunk&)’:
/opt/Private/librtcdcpp/include/rtcdcpp/Chunk.hpp:52: error: class ‘rtcdcpp::Chunk’ does not have any field named ‘len’
/opt/Private/librtcdcpp/include/rtcdcpp/Chunk.hpp:52: error: ‘const class rtcdcpp::Chunk’ has no member named ‘len’
/opt/Private/librtcdcpp/include/rtcdcpp/Chunk.hpp:52: error: class ‘rtcdcpp::Chunk’ does not have any field named ‘data’
/opt/Private/librtcdcpp/include/rtcdcpp/Chunk.hpp:52: error: ‘len’ was not declared in this scope
/opt/Private/librtcdcpp/include/rtcdcpp/Chunk.hpp:52: error: ‘data’ was not declared in this scope
/opt/Private/librtcdcpp/include/rtcdcpp/Chunk.hpp:52: error: ‘const class rtcdcpp::Chunk’ has no member named ‘data’
/opt/Private/librtcdcpp/include/rtcdcpp/Chunk.hpp:52: error: ‘const class rtcdcpp::Chunk’ has no member named ‘len’
/opt/Private/librtcdcpp/include/rtcdcpp/Chunk.hpp: In member function ‘rtcdcpp::Chunk& rtcdcpp::Chunk::operator=(const rtcdcpp::Chunk&)’:
/opt/Private/librtcdcpp/include/rtcdcpp/Chunk.hpp:56: error: ‘data’ was not declared in this scope
/opt/Private/librtcdcpp/include/rtcdcpp/Chunk.hpp:57: error: ‘len’ was not declared in this scope
/opt/Private/librtcdcpp/include/rtcdcpp/Chunk.hpp:58: error: type ‘<type error>’ argument given to ‘delete’, expected pointer
/opt/Private/librtcdcpp/include/rtcdcpp/Chunk.hpp:60: error: ‘len’ was not declared in this scope
/opt/Private/librtcdcpp/include/rtcdcpp/Chunk.hpp:60: error: ‘const class rtcdcpp::Chunk’ has no member named ‘len’
/opt/Private/librtcdcpp/include/rtcdcpp/Chunk.hpp:61: error: ‘data’ was not declared in this scope
/opt/Private/librtcdcpp/include/rtcdcpp/Chunk.hpp:62: error: ‘const class rtcdcpp::Chunk’ has no member named ‘data’
/opt/Private/librtcdcpp/include/rtcdcpp/Chunk.hpp:62: error: ‘const class rtcdcpp::Chunk’ has no member named ‘len’
/opt/Private/librtcdcpp/include/rtcdcpp/Chunk.hpp: In destructor ‘rtcdcpp::Chunk::~Chunk()’:
/opt/Private/librtcdcpp/include/rtcdcpp/Chunk.hpp:66: error: ‘data’ was not declared in this scope
/opt/Private/librtcdcpp/include/rtcdcpp/Chunk.hpp: In member function ‘size_t rtcdcpp::Chunk::Size() const’:
/opt/Private/librtcdcpp/include/rtcdcpp/Chunk.hpp:68: error: ‘len’ was not declared in this scope
/opt/Private/librtcdcpp/include/rtcdcpp/Chunk.hpp: In member function ‘uint8_t* rtcdcpp::Chunk::Data() const’:
/opt/Private/librtcdcpp/include/rtcdcpp/Chunk.hpp:70: error: ‘data’ was not declared in this scope
/opt/Private/librtcdcpp/include/rtcdcpp/Chunk.hpp: At global scope:
/opt/Private/librtcdcpp/include/rtcdcpp/Chunk.hpp:73: error: expected nested-name-specifier before ‘ChunkPtr’
/opt/Private/librtcdcpp/include/rtcdcpp/Chunk.hpp:73: error: ‘ChunkPtr’ has not been declared
/opt/Private/librtcdcpp/include/rtcdcpp/Chunk.hpp:73: error: expected ‘;’ before ‘=’ token
/opt/Private/librtcdcpp/include/rtcdcpp/Chunk.hpp:73: error: expected unqualified-id before ‘=’ token
In file included from /opt/Private/librtcdcpp/src/DataChannel.cpp:34:
/opt/Private/librtcdcpp/include/rtcdcpp/DataChannel.hpp:89: error: ‘ChunkPtr’ was not declared in this scope
/opt/Private/librtcdcpp/include/rtcdcpp/DataChannel.hpp:89: error: template argument 1 is invalid
/opt/Private/librtcdcpp/include/rtcdcpp/DataChannel.hpp:95: error: ‘ChunkPtr’ has not been declared
/opt/Private/librtcdcpp/include/rtcdcpp/DataChannel.hpp:155: error: ‘ChunkPtr’ was not declared in this scope
/opt/Private/librtcdcpp/include/rtcdcpp/DataChannel.hpp:155: error: template argument 1 is invalid
In file included from /opt/Private/librtcdcpp/include/rtcdcpp/PeerConnection.hpp:30,
                 from /opt/Private/librtcdcpp/src/DataChannel.cpp:35:
/opt/Private/librtcdcpp/include/rtcdcpp/ChunkQueue.hpp:47: error: ‘ChunkPtr’ was not declared in this scope
/opt/Private/librtcdcpp/include/rtcdcpp/ChunkQueue.hpp:47: error: template argument 1 is invalid
/opt/Private/librtcdcpp/include/rtcdcpp/ChunkQueue.hpp:47: error: template argument 2 is invalid
/opt/Private/librtcdcpp/include/rtcdcpp/ChunkQueue.hpp:60: error: ‘ChunkPtr’ has not been declared
/opt/Private/librtcdcpp/include/rtcdcpp/ChunkQueue.hpp:69: error: ‘ChunkPtr’ does not name a type
/opt/Private/librtcdcpp/include/rtcdcpp/ChunkQueue.hpp: In member function ‘void rtcdcpp::ChunkQueue::push(int)’:
/opt/Private/librtcdcpp/include/rtcdcpp/ChunkQueue.hpp:65: error: request for member ‘push’ in ‘((rtcdcpp::ChunkQueue*)this)->rtcdcpp::ChunkQueue::chunk_queue’, which is of non-class type ‘int’
/opt/Private/librtcdcpp/include/rtcdcpp/ChunkQueue.hpp: In member function ‘bool rtcdcpp::ChunkQueue::empty() const’:
/opt/Private/librtcdcpp/include/rtcdcpp/ChunkQueue.hpp:86: error: request for member ‘empty’ in ‘((const rtcdcpp::ChunkQueue*)this)->rtcdcpp::ChunkQueue::chunk_queue’, which is of non-class type ‘const int’
In file included from /usr/include/spdlog/common.h:21,
                 from /usr/include/spdlog/spdlog.h:12,
                 from /opt/Private/librtcdcpp/include/rtcdcpp/Logging.hpp:33,
                 from /opt/Private/librtcdcpp/include/rtcdcpp/PeerConnection.hpp:33,
                 from /opt/Private/librtcdcpp/src/DataChannel.cpp:35:
/usr/include/spdlog/details/null_mutex.h: At global scope:
/usr/include/spdlog/details/null_mutex.h:33: error: ‘std::memory_order’ has not been declared
In file included from /usr/include/spdlog/spdlog.h:12,
                 from /opt/Private/librtcdcpp/include/rtcdcpp/Logging.hpp:33,
                 from /opt/Private/librtcdcpp/include/rtcdcpp/PeerConnection.hpp:33,
                 from /opt/Private/librtcdcpp/src/DataChannel.cpp:35:
/usr/include/spdlog/common.h:53: error: expected nested-name-specifier before ‘log_clock’
/usr/include/spdlog/common.h:53: error: ‘log_clock’ has not been declared
/usr/include/spdlog/common.h:53: error: expected ‘;’ before ‘=’ token
/usr/include/spdlog/common.h:53: error: expected unqualified-id before ‘=’ token
/usr/include/spdlog/common.h:54: error: expected nested-name-specifier before ‘sink_ptr’
/usr/include/spdlog/common.h:54: error: ‘sink_ptr’ has not been declared
/usr/include/spdlog/common.h:54: error: expected ‘;’ before ‘=’ token
/usr/include/spdlog/common.h:54: error: expected unqualified-id before ‘=’ token
/usr/include/spdlog/common.h:55: error: expected nested-name-specifier before ‘sinks_init_list’
/usr/include/spdlog/common.h:55: error: ‘sinks_init_list’ has not been declared
/usr/include/spdlog/common.h:55: error: expected ‘;’ before ‘=’ token
/usr/include/spdlog/common.h:55: error: expected unqualified-id before ‘=’ token
/usr/include/spdlog/common.h:56: error: expected nested-name-specifier before ‘formatter_ptr’
/usr/include/spdlog/common.h:56: error: ‘formatter_ptr’ has not been declared
/usr/include/spdlog/common.h:56: error: expected ‘;’ before ‘=’ token
/usr/include/spdlog/common.h:56: error: expected unqualified-id before ‘=’ token
/usr/include/spdlog/common.h:60: error: expected nested-name-specifier before ‘level_t’
/usr/include/spdlog/common.h:60: error: ‘level_t’ has not been declared
/usr/include/spdlog/common.h:60: error: expected ‘;’ before ‘=’ token
/usr/include/spdlog/common.h:60: error: expected unqualified-id before ‘=’ token
/usr/include/spdlog/common.h:63: error: expected nested-name-specifier before ‘log_err_handler’
/usr/include/spdlog/common.h:63: error: ‘log_err_handler’ has not been declared
/usr/include/spdlog/common.h:63: error: expected ‘;’ before ‘=’ token
/usr/include/spdlog/common.h:63: error: expected unqualified-id before ‘=’ token
/usr/include/spdlog/common.h:124: error: expected ‘;’ before ‘noexcept’
/usr/include/spdlog/common.h:128: error: expected ‘;’ before ‘private’
/usr/include/spdlog/common.h:116: error: looser throw specifier for ‘virtual spdlog::spdlog_ex::~spdlog_ex()’
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/exception:63: error:   overriding ‘virtual std::exception::~exception() throw ()’
/usr/include/spdlog/common.h:139: error: expected nested-name-specifier before ‘filename_t’
/usr/include/spdlog/common.h:139: error: ‘filename_t’ has not been declared
/usr/include/spdlog/common.h:139: error: expected ‘;’ before ‘=’ token
/usr/include/spdlog/common.h:139: error: expected unqualified-id before ‘=’ token
In file included from /usr/include/spdlog/details/log_msg.h:9,
                 from /usr/include/spdlog/sinks/sink.h:9,
                 from /usr/include/spdlog/sinks/base_sink.h:13,
                 from /usr/include/spdlog/logger.h:15,
                 from /usr/include/spdlog/spdlog.h:13,
                 from /opt/Private/librtcdcpp/include/rtcdcpp/Logging.hpp:33,
                 from /opt/Private/librtcdcpp/include/rtcdcpp/PeerConnection.hpp:33,
                 from /opt/Private/librtcdcpp/src/DataChannel.cpp:35:
/usr/include/spdlog/details/os.h:56: error: ‘spdlog::log_clock’ has not been declared
/usr/include/spdlog/details/os.h:56: error: expected initializer before ‘now’
/usr/include/spdlog/details/os.h: In function ‘tm spdlog::details::os::localtime()’:
/usr/include/spdlog/details/os.h:87: error: ‘nullptr’ was not declared in this scope
/usr/include/spdlog/details/os.h: In function ‘tm spdlog::details::os::gmtime()’:
/usr/include/spdlog/details/os.h:107: error: ‘nullptr’ was not declared in this scope
/usr/include/spdlog/details/os.h: At global scope:
/usr/include/spdlog/details/os.h:135: error: expected constructor, destructor, or type conversion before ‘static’
/usr/include/spdlog/details/os.h:136: error: expected constructor, destructor, or type conversion before ‘static’
/usr/include/spdlog/details/os.h:141: error: expected ‘,’ or ‘...’ before ‘&’ token
/usr/include/spdlog/details/os.h: In function ‘int spdlog::details::os::fopen_s(FILE**, int)’:
/usr/include/spdlog/details/os.h:151: error: ‘filename’ was not declared in this scope
/usr/include/spdlog/details/os.h:151: error: ‘mode’ was not declared in this scope
/usr/include/spdlog/details/os.h:152: error: ‘nullptr’ was not declared in this scope
/usr/include/spdlog/details/os.h: At global scope:
/usr/include/spdlog/details/os.h:156: error: expected ‘,’ or ‘...’ before ‘&’ token
/usr/include/spdlog/details/os.h: In function ‘int spdlog::details::os::remove(int)’:
/usr/include/spdlog/details/os.h:161: error: ‘filename’ was not declared in this scope
/usr/include/spdlog/details/os.h: At global scope:
/usr/include/spdlog/details/os.h:165: error: expected ‘,’ or ‘...’ before ‘&’ token
/usr/include/spdlog/details/os.h: In function ‘int spdlog::details::os::rename(int)’:
/usr/include/spdlog/details/os.h:170: error: ‘filename1’ was not declared in this scope
/usr/include/spdlog/details/os.h:170: error: ‘filename2’ was not declared in this scope
/usr/include/spdlog/details/os.h: At global scope:
/usr/include/spdlog/details/os.h:176: error: expected ‘,’ or ‘...’ before ‘&’ token
/usr/include/spdlog/details/os.h: In function ‘bool spdlog::details::os::file_exists(int)’:
/usr/include/spdlog/details/os.h:187: error: ‘filename’ was not declared in this scope
/usr/include/spdlog/details/os.h: In function ‘size_t spdlog::details::os::filesize(FILE*)’:
/usr/include/spdlog/details/os.h:197: error: ‘nullptr’ was not declared in this scope
In file included from /usr/include/spdlog/details/log_msg.h:9,
                 from /usr/include/spdlog/sinks/sink.h:9,
                 from /usr/include/spdlog/sinks/base_sink.h:13,
                 from /usr/include/spdlog/logger.h:15,
                 from /usr/include/spdlog/spdlog.h:13,
                 from /opt/Private/librtcdcpp/include/rtcdcpp/Logging.hpp:33,
                 from /opt/Private/librtcdcpp/include/rtcdcpp/PeerConnection.hpp:33,
                 from /opt/Private/librtcdcpp/src/DataChannel.cpp:35:
/usr/include/spdlog/details/os.h: At global scope:
/usr/include/spdlog/details/os.h:326: error: expected ‘,’ or ‘...’ before ‘&’ token
/usr/include/spdlog/details/os.h: In function ‘std::string spdlog::details::os::filename_to_str(int)’:
/usr/include/spdlog/details/os.h:328: error: ‘filename’ was not declared in this scope
/usr/include/spdlog/details/os.h: In function ‘std::string spdlog::details::os::errno_str(int)’:
/usr/include/spdlog/details/os.h:337: error: ‘constexpr’ was not declared in this scope
/usr/include/spdlog/details/os.h:337: error: expected ‘;’ before ‘auto’
/usr/include/spdlog/details/os.h:352: error: ‘buf_size’ was not declared in this scope
In file included from /usr/include/spdlog/sinks/sink.h:9,
                 from /usr/include/spdlog/sinks/base_sink.h:13,
                 from /usr/include/spdlog/logger.h:15,
                 from /usr/include/spdlog/spdlog.h:13,
                 from /opt/Private/librtcdcpp/include/rtcdcpp/Logging.hpp:33,
                 from /opt/Private/librtcdcpp/include/rtcdcpp/PeerConnection.hpp:33,
                 from /opt/Private/librtcdcpp/src/DataChannel.cpp:35:
/usr/include/spdlog/details/log_msg.h: At global scope:
/usr/include/spdlog/details/log_msg.h:40: error: ‘log_clock’ has not been declared
/usr/include/spdlog/details/log_msg.h:40: error: expected ‘;’ before ‘time’
/usr/include/spdlog/details/log_msg.h: In constructor ‘spdlog::details::log_msg::log_msg(const std::string*, spdlog::level::level_enum)’:
/usr/include/spdlog/details/log_msg.h:25: error: ‘now’ is not a member of ‘spdlog::details::os’
In file included from /usr/include/spdlog/sinks/base_sink.h:14,
                 from /usr/include/spdlog/logger.h:15,
                 from /usr/include/spdlog/spdlog.h:13,
                 from /opt/Private/librtcdcpp/include/rtcdcpp/Logging.hpp:33,
                 from /opt/Private/librtcdcpp/include/rtcdcpp/PeerConnection.hpp:33,
                 from /opt/Private/librtcdcpp/src/DataChannel.cpp:35:
/usr/include/spdlog/formatter.h: At global scope:
/usr/include/spdlog/formatter.h:35: error: expected ‘;’ before ‘override’
In file included from /usr/include/spdlog/formatter.h:44,
                 from /usr/include/spdlog/sinks/base_sink.h:14,
                 from /usr/include/spdlog/logger.h:15,
                 from /usr/include/spdlog/spdlog.h:13,
                 from /opt/Private/librtcdcpp/include/rtcdcpp/Logging.hpp:33,
                 from /opt/Private/librtcdcpp/include/rtcdcpp/PeerConnection.hpp:33,
                 from /opt/Private/librtcdcpp/src/DataChannel.cpp:35:
/usr/include/spdlog/details/pattern_formatter_impl.h:41: error: expected ‘;’ before ‘override’
/usr/include/spdlog/details/pattern_formatter_impl.h:45: error: expected ‘;’ before ‘}’ token
/usr/include/spdlog/details/pattern_formatter_impl.h:51: error: expected ‘;’ before ‘override’
/usr/include/spdlog/details/pattern_formatter_impl.h:55: error: expected ‘;’ before ‘}’ token
/usr/include/spdlog/details/pattern_formatter_impl.h:60: error: expected ‘;’ before ‘override’
/usr/include/spdlog/details/pattern_formatter_impl.h:64: error: expected ‘;’ before ‘}’ token
/usr/include/spdlog/details/pattern_formatter_impl.h:84: error: expected ‘;’ before ‘override’
/usr/include/spdlog/details/pattern_formatter_impl.h:88: error: expected ‘;’ before ‘}’ token
/usr/include/spdlog/details/pattern_formatter_impl.h:94: error: expected ‘;’ before ‘override’
/usr/include/spdlog/details/pattern_formatter_impl.h:98: error: expected ‘;’ before ‘}’ token
/usr/include/spdlog/details/pattern_formatter_impl.h:104: error: expected ‘;’ before ‘override’
/usr/include/spdlog/details/pattern_formatter_impl.h:108: error: expected ‘;’ before ‘}’ token
In file included from /usr/include/spdlog/formatter.h:44,
                 from /usr/include/spdlog/sinks/base_sink.h:14,
                 from /usr/include/spdlog/logger.h:15,
                 from /usr/include/spdlog/spdlog.h:13,
                 from /opt/Private/librtcdcpp/include/rtcdcpp/Logging.hpp:33,
                 from /opt/Private/librtcdcpp/include/rtcdcpp/PeerConnection.hpp:33,
                 from /opt/Private/librtcdcpp/src/DataChannel.cpp:35:
/usr/include/spdlog/details/pattern_formatter_impl.h:114: error: expected ‘;’ before ‘override’
/usr/include/spdlog/details/pattern_formatter_impl.h:118: error: expected ‘;’ before ‘}’ token
/usr/include/spdlog/details/pattern_formatter_impl.h:139: error: expected ‘;’ before ‘override’
/usr/include/spdlog/details/pattern_formatter_impl.h:144: error: expected ‘;’ before ‘}’ token
/usr/include/spdlog/details/pattern_formatter_impl.h:150: error: expected ‘;’ before ‘override’
/usr/include/spdlog/details/pattern_formatter_impl.h:154: error: expected ‘;’ before ‘}’ token
/usr/include/spdlog/details/pattern_formatter_impl.h:161: error: expected ‘;’ before ‘override’
/usr/include/spdlog/details/pattern_formatter_impl.h:165: error: expected ‘;’ before ‘}’ token
/usr/include/spdlog/details/pattern_formatter_impl.h:171: error: expected ‘;’ before ‘override’
/usr/include/spdlog/details/pattern_formatter_impl.h:175: error: expected ‘;’ before ‘}’ token
/usr/include/spdlog/details/pattern_formatter_impl.h:180: error: expected ‘;’ before ‘override’
/usr/include/spdlog/details/pattern_formatter_impl.h:184: error: expected ‘;’ before ‘}’ token
/usr/include/spdlog/details/pattern_formatter_impl.h:189: error: expected ‘;’ before ‘override’
/usr/include/spdlog/details/pattern_formatter_impl.h:193: error: expected ‘;’ before ‘}’ token
/usr/include/spdlog/details/pattern_formatter_impl.h:198: error: expected ‘;’ before ‘override’
/usr/include/spdlog/details/pattern_formatter_impl.h:202: error: expected ‘;’ before ‘}’ token
/usr/include/spdlog/details/pattern_formatter_impl.h:207: error: expected ‘;’ before ‘override’
/usr/include/spdlog/details/pattern_formatter_impl.h:211: error: expected ‘;’ before ‘}’ token
/usr/include/spdlog/details/pattern_formatter_impl.h:216: error: expected ‘;’ before ‘override’
/usr/include/spdlog/details/pattern_formatter_impl.h:220: error: expected ‘;’ before ‘}’ token
/usr/include/spdlog/details/pattern_formatter_impl.h:225: error: expected ‘;’ before ‘override’
/usr/include/spdlog/details/pattern_formatter_impl.h:229: error: expected ‘;’ before ‘}’ token
/usr/include/spdlog/details/pattern_formatter_impl.h:234: error: expected ‘;’ before ‘override’
/usr/include/spdlog/details/pattern_formatter_impl.h:240: error: expected ‘;’ before ‘}’ token
/usr/include/spdlog/details/pattern_formatter_impl.h:245: error: expected ‘;’ before ‘override’
/usr/include/spdlog/details/pattern_formatter_impl.h:251: error: expected ‘;’ before ‘}’ token
/usr/include/spdlog/details/pattern_formatter_impl.h:256: error: expected ‘;’ before ‘override’
/usr/include/spdlog/details/pattern_formatter_impl.h:262: error: expected ‘;’ before ‘}’ token
/usr/include/spdlog/details/pattern_formatter_impl.h:267: error: expected ‘;’ before ‘override’
/usr/include/spdlog/details/pattern_formatter_impl.h:271: error: expected ‘;’ before ‘}’ token
/usr/include/spdlog/details/pattern_formatter_impl.h:277: error: expected ‘;’ before ‘override’
/usr/include/spdlog/details/pattern_formatter_impl.h:281: error: expected ‘;’ before ‘}’ token
/usr/include/spdlog/details/pattern_formatter_impl.h:286: error: expected ‘;’ before ‘override’
/usr/include/spdlog/details/pattern_formatter_impl.h:290: error: expected ‘;’ before ‘}’ token
/usr/include/spdlog/details/pattern_formatter_impl.h:295: error: expected ‘;’ before ‘override’
/usr/include/spdlog/details/pattern_formatter_impl.h:299: error: expected ‘;’ before ‘}’ token
/usr/include/spdlog/details/pattern_formatter_impl.h:306: error: a call to a constructor cannot appear in a constant-expression
/usr/include/spdlog/details/pattern_formatter_impl.h:306: error: ISO C++ forbids initialization of member ‘cache_refresh’
/usr/include/spdlog/details/pattern_formatter_impl.h:306: error: making ‘cache_refresh’ static
/usr/include/spdlog/details/pattern_formatter_impl.h:306: error: invalid in-class initialization of static data member of non-integral type ‘const std::chrono::seconds’
/usr/include/spdlog/details/pattern_formatter_impl.h:313: error: expected ‘;’ before ‘override’
/opt/Private/librtcdcpp/src/DataChannel.cpp:117: error: expected ‘;’ at end of input
/opt/Private/librtcdcpp/src/DataChannel.cpp:117: error: expected ‘}’ at end of input
In file included from /usr/include/spdlog/formatter.h:44,
                 from /usr/include/spdlog/sinks/base_sink.h:14,
                 from /usr/include/spdlog/logger.h:15,
                 from /usr/include/spdlog/spdlog.h:13,
                 from /opt/Private/librtcdcpp/include/rtcdcpp/Logging.hpp:33,
                 from /opt/Private/librtcdcpp/include/rtcdcpp/PeerConnection.hpp:33,
                 from /opt/Private/librtcdcpp/src/DataChannel.cpp:35:
/usr/include/spdlog/details/pattern_formatter_impl.h: In constructor ‘spdlog::details::z_formatter::z_formatter()’:
/usr/include/spdlog/details/pattern_formatter_impl.h:308: error: class ‘spdlog::details::z_formatter’ does not have any field named ‘_last_update’
/usr/include/spdlog/details/pattern_formatter_impl.h: At global scope:
/usr/include/spdlog/details/pattern_formatter_impl.h:309: error: expected unqualified-id at end of input
/usr/include/spdlog/details/pattern_formatter_impl.h:309: error: expected ‘}’ at end of input
/usr/include/spdlog/details/pattern_formatter_impl.h:309: error: expected ‘}’ at end of input
make[2]: *** [CMakeFiles/rtcdcpp.dir/src/DataChannel.cpp.o] Error 1
make[1]: *** [CMakeFiles/rtcdcpp.dir/all] Error 2
make: *** [all] Error 2

**Comment by PowerInside** [comment]
Looks like your C++ compiler doesn't support C11. Try installing a newer version.

GCC C11 status: https://gcc.gnu.org/wiki/C11Status
